In [1]:
import numpy as np

In [2]:
l1=[12,23,34,45]

In [3]:
df=np.array(l1)

In [4]:
df

array([12, 23, 34, 45])

In [5]:
print(df)

[12 23 34 45]


In [6]:
type(df)

numpy.ndarray

In [7]:
type(l1)

list

In [8]:
type(df)

numpy.ndarray

In [9]:
s=[10,20,30,40,50,60,70,80,90,100]

In [10]:
df1=np.array(s)

In [11]:
df1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
type(df1)

numpy.ndarray

In [13]:
print(df.dtype)

int32


In [14]:
print(df1.dtype)

int32


In [15]:
df.shape

(4,)

In [16]:
df.size

4

In [17]:
l2=[[1,2,3],[5,6,7],[6,7,8]]

In [18]:
df2=np.array(l2)

In [19]:
df2

array([[1, 2, 3],
       [5, 6, 7],
       [6, 7, 8]])

In [20]:
df2.shape    # no of rows and columns present in array

(3, 3)

In [21]:
df2.size   # no of elements present in array

9

In [22]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(4,21)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [26]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [28]:
np.zeros(31)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,3))  # 5 rows and 4 col

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros((4,5))    #4 rows and 5 col

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.random.randint(1,100)    #generate random number between 1 to 100

91

In [33]:
np.random.randint(1,100)

7

In [34]:
 np.random.randint(20,200)

158

In [35]:
np.random.randint(20,200,3)  # 3 random numbers between 20,200

array([129, 101,  86])

In [36]:
np.random.randint(1,501,20)   # 20 random numbers between 1 to 500

array([115, 255, 368, 407, 368, 326, 299, 217, 280, 411, 396, 258, 206,
       301, 130, 211, 121, 459,  60, 345])

In [37]:
f=[0,1,2,3,4,5,6,7,8]
df3=np.array(f)

In [38]:
df3.shape

(9,)

In [39]:
df3.size

9

In [40]:
df3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
t=[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
df4=np.array(t)

In [7]:
df4.shape

(4, 4)

In [8]:
df4.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [9]:
df4.size

16

In [5]:
arr=np.arange(21)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
arr[4]

4

In [12]:
arr[20]

20

In [13]:
arr[-1]

20

In [14]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [15]:
arr[-5:]

array([16, 17, 18, 19, 20])

In [16]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
arr[3]=30    #broadcasting 3 replace by 30

In [10]:
arr

array([ 0,  1,  2, 30,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr[2]=9

In [13]:
arr

array([ 0,  1,  9, 30,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
arr[10]=20   # 10 replace by 20

In [21]:
arr

array([ 0,  1,  2, 30,  4,  5,  6,  7,  8,  9, 20, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [22]:
arr[4:8]=50

In [23]:
arr

array([ 0,  1,  2, 30, 50, 50, 50, 50,  8,  9, 20, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
arr[0:3]=100

In [15]:
arr

array([100, 100, 100,  30,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [16]:
df4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
df4[0]

array([0, 1, 2, 3])

In [61]:
df4[1,2]

6

In [21]:
df4[2:,2:-1]

array([[10],
       [14]])

In [33]:
df4[2,-2]

10

In [62]:
df4[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [63]:
df4[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [64]:
df4[2:4,2:4]

array([[10, 11],
       [14, 15]])

In [3]:
arr2=np.ones((11,11))

In [4]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
for i in range(11):
    arr2[i]=i
arr2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [13]:
zeros=np.zeros((4,4))

In [15]:
zeros(0,0)=1
zeros(1,1)=1
zeros(2,2)=1
zeros(3,3)=1
zeros

SyntaxError: cannot assign to function call (492165317.py, line 1)

In [7]:
import numpy as np

In [72]:
array=np.array(['a','b',2,3])

In [73]:
array

array(['a', 'b', '2', '3'], dtype='<U11')

In [74]:
type(array)

numpy.ndarray

In [75]:
array.dtype

dtype('<U11')

In [77]:
zeros=np.zeros((4,4))

In [78]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
zeros[0,0]=1
zeros[1,1]=1
zeros[2,2]=1
zeros[3,3]=1
zeros

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
zeros[0,0]=1
zeros[1,1]=1
zeros[2,2]=1
zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
ones=np.ones((3,3))*6

In [40]:
ones

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [92]:
ones=np.ones((4,4))*5

In [93]:
ones

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [95]:
np.eye(3)*3

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [97]:
np.eye(4)*7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [104]:
np.random.rand(1)   #generate no. mid of 0 to 1 (rows and column)

array([0.22376658])

In [105]:
np.random.rand(1,3)

array([[0.31172422, 0.24127836, 0.5155041 ]])

In [106]:
np.random.rand(4,5)

array([[0.3107064 , 0.62970405, 0.90047595, 0.8178566 , 0.21358765],
       [0.7480952 , 0.96212125, 0.70530469, 0.6114556 , 0.07296896],
       [0.35788086, 0.3340681 , 0.14687954, 0.32420405, 0.08382696],
       [0.69891452, 0.25337868, 0.12963285, 0.63091887, 0.27770779]])

In [107]:
np.random.randn(25)   #all type value involved

array([ 0.77823633, -0.65758472,  1.04023348,  0.22183466,  1.04464095,
       -0.66874149,  1.65136229,  0.44876892,  0.47696023,  0.08597069,
        0.42823072, -0.57254001,  0.89045081, -0.37280512, -1.38970419,
       -1.18157028, -0.42229982,  0.67962629,  1.72012641, -0.77700262,
       -0.65657937, -0.73849064, -0.4691893 ,  0.18729132,  0.21026736])

In [41]:
df5=np.arange(6)

In [42]:
df5

array([0, 1, 2, 3, 4, 5])

In [44]:
df5[df5>2]

array([3, 4, 5])

In [45]:
df5[df5<3]

array([0, 1, 2])

In [109]:
array1d=np.arange(11)

In [110]:
array1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
array1d>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [112]:
array1d[array1d>4]

array([ 5,  6,  7,  8,  9, 10])

In [113]:
array1d[array1d>8]

array([ 9, 10])

In [114]:
array1d*array1d

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [115]:
array1d**3 #cube

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [117]:
array1d**array1d #suqare

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [118]:
array1d.sum() #sum 

55

In [121]:
sum(array1d)

55

In [122]:
array1d.mean()    #mean of avg

5.0

In [123]:
array1d.std() #standard deviation

3.1622776601683795

In [125]:
darray=np.array([[12,34,45],[67,89,90]])

In [126]:
darray

array([[12, 34, 45],
       [67, 89, 90]])

In [127]:
darray.sum()

337

In [128]:
darray.sum(axis=0)   #0 means column wise

array([ 79, 123, 135])

In [129]:
darray.sum(axis=1) #1 means row wise 

array([ 91, 246])

In [130]:
darray

array([[12, 34, 45],
       [67, 89, 90]])

In [131]:
np.sort(darray)

array([[12, 34, 45],
       [67, 89, 90]])

In [133]:
sort_array=np.array([[12,56,10],[56,90,12],[50,90,10]])
sort_array

array([[12, 56, 10],
       [56, 90, 12],
       [50, 90, 10]])

In [134]:
np.sort(sort_array)

array([[10, 12, 56],
       [12, 56, 90],
       [10, 50, 90]])

In [135]:
np.sort(sort_array,axis=0)

array([[12, 56, 10],
       [50, 90, 10],
       [56, 90, 12]])

In [136]:
simple=np.array([34,78,90,12,10])

In [138]:
fd=np.sort(simple)

In [141]:
fd     #ascending by default

array([10, 12, 34, 78, 90])

In [142]:
fd[::-1]       # reverse array for descending 

array([90, 78, 34, 12, 10])